//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleCalculatorResult
    {
        public int Id { get; set; }
        public string FunctionName { get; set; }
        public string FunctionTotal { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
